variable "monitor_parametros" {
  type = list(object({
		name_cm = optional(string)
		monitor_type = optional(string)
		monitor_msg = optional(string)
		monitor_query = optional(string)
		critical_value = optional(number)
		warning_value = optional(number)
		criticalr_value = optional(number)
		trigg_w = optional(string)
		rec_w = optional(string)   
		monitor_notify_nodata = optional(bool)
		renotify_interval = optional(number)
		new_group_delay = optional(number)
		monitor_tags = optional(list(string))
		no_data_fr = optional(number)
		monitor_renotify_s = optional(list(string))
		monitor_renotify_o = optional(number)
		monitor_timeout_h = optional(number)
		monitor_on_missing_data = optional(string)
		monitor_enable_logs_sample = optional(bool)
		groupby_simple_monitor = optional(bool)
		monitor_id = optional(string)
		monitor_path = optional(string)
  }))
  default = null
}